--- # directory deletion
- name: my test playbook
  hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: deleting a directory
      file:
        path: /home/ansible/haridir
        state: absent
