---
- name: my conditionals playbook
  hosts: all
  become: true


  tasks:
    - name: installing httpd package
      yum:
        name: docker
        state: installed
      when: ansible_os_family == "RedHat"

    - name: start httpd service
      service:
        name: docker
        state: started
      when: ansible_os_family == "RedHat"

    - name: installing apache2 package
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: start apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"







